- name: install tomcat 10 on ubuntu 20.4
  hosts: all
  become: yes
  tasks:
    - name: Install apache httpd  (state=present is optional)
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: Add the user tomcat
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present