- name: install tomcat 10 on ubuntu 20.4
  hosts: all
  become: yes
  vars:
    Java_package: openjdk-11-jdk
    user_name: tomcat
    user_group: tomcat
    user_home: /opt/tomcat
    user_shell: /bin/false
    Version: 10.1.6
    Major_Version: 10
    tomcat_service_name: tomcat.service

  tasks:
    - name: Install Java
      ansible.builtin.apt:
        name: '{{Java_package}}'
        update_cache: yes
        state: present
    - name: Add the user tomcat
      ansible.builtin.group:
        name: '{{ user_name }}'
        state: present
    - name: Add the user tomcat
      ansible.builtin.user:
        name: '{{ user_name }}'
        create_home: yes
        group: '{{ user_group }}' 
        home: '{{ user_home }}'
        shell: '{{ user_shell }}'
        state: present
    - name: download tomcat {{ Version }}'
      ansible.builtin.get_url:
        url: https://www-eu.apache.org/dist/tomcat/tomcat-{{ Major_Version }}/v{{ Version }}/bin/apache-tomcat-{{ Version }}.tar.gz
        dest: /tmp/apache-tomcat-{{ Version }}.tar.gz
    - name: download tomcat {{ Version }}
      ansible.builtin.unarchive:
        src: https://www-eu.apache.org/dist/tomcat/tomcat-{{ Major_Version }}/v{{ Version }}/bin/apache-tomcat-{{ Version }}.tar.gz
        remote_src: yes
        dest: /opt/tomcat/
    - name: create a symbolic link
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-{{ Version }}
        dest: /opt/tomcat/latest
        state: link
    - name: change permissions
      ansible.builtin.file:
        dest: /opt/tomcat
        recurse: true
        owner: '{{ user_name }}'
        group: '{{ user_group }}' 
        state: directory
    - name: Running command
      ansible.builtin.command: sudo sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: '{{ tomcat_service_name }}'
        dest: /etc/systemd/system/'{{ tomcat_service_name }}'
        owner: '{{ user_name }}'
        group: '{{ user_group }}' 
    - name: reload daemon and start tomcat
      ansible.builtin.systemd:
        name: '{{ tomcat_service_name }}'
        daemon_reload: yes
        enabled: yes
        state: started
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: '{{ tomcat_service_name }}'
        dest: /etc/systemd/system/'{{ tomcat_service_name }}'
        owner: '{{ user_name }}'
        group: '{{ user_group }}' 
    - name: Adding tomcat users
      ansible.builtin.copy:
        src: tomcat.user.xml
        dest: /opt/tomcat/latest/conf/tomcat-users.xml
        owner: '{{ user_name }}'
        group: '{{ user_group }}' 
    - name: To enable manager interface
      ansible.builtin.copy:
        src: context.xml
        dest: /opt/tomcat/latest/webapps/manager/META-INF/context.xml
        owner: '{{ user_name }}'
        group: '{{ user_group }}'  
    - name: To enable host Manager interface
      ansible.builtin.copy:
        src: HMCintext.xml
        dest: /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
        owner: '{{ user_name }}'
        group: '{{ user_group }}' 
    - name: restart tomcat
      ansible.builtin.systemd:
        name: '{{ tomcat_service_name }}'
        state: restarted