- name: install tomcat 10 on ubuntu 20.4
  hosts: all
  become: yes
  tasks:
    - name: Install apache httpd  (state=present is optional)
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: Add the user tomcat
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: Add the user tomcat
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present
    - name: download tomcat 10.1.6
      ansible.builtin.get_url:
        url: https://www-eu.apache.org/dist/tomcat/tomcat-10/v10.1.6/bin/apache-tomcat-10.1.6.tar.gz
        dest: /tmp/apache-tomcat-10.1.6.tar.gz
    - name: download toomcat 10.1.6
      ansible.builtin.unarchive:
        src: https://www-eu.apache.org/dist/tomcat/tomcat-10/v10.1.6/bin/apache-tomcat-10.1.6.tar.gz
        remote_src: yes
        dest: /opt/tomcat/
    - name: create a symbolic link
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-10.1.6
        dest: /opt/tomcat/latest
        recurse: yes
        owner: tomcat
        group: tomcat
        state: link
